- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/TraceContextHolder.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/integration/TraceChannelInterceptor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/integration/TraceContextPropagationChannelInterceptor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/TraceContextHolderTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/integration/TraceChannelInterceptorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/integration/TraceContextPropagationChannelInterceptorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptorTests.java
> Use ThreadLocal.remove() rather than .set(null)

- spring-cloud-sleuth-zipkin/docker-compose.yml
Tested with `spring-cloud-sleuth-sample-zipkin`, except I needed to change application.yml to use it (as docker isn't on localhost).
Noob q: What's the CLI arg equiv of:
```diff
index 20f9a1c..7d196e0 100644
--- a/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/resources/application.yml
+++ b/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/resources/application.yml
@@ -4,6 +4,8 @@ server:
spring:
application:
name: testSleuthZipkin
+  zipkin:
+    host: 192.168.99.100
logging:
pattern:
```
> Updates docker-compose to zipkin 1.9.0

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
Come to think of it - it's better to remove the `ConditionalOnMissingBean` since we already wrapped the whole configuration file with `ConditionalOnMissingProperty`
> Removed ConditionalOnMissingBean. Fixes #42

- README.adoc
- pom.xml
- spring-cloud-sleuth-zipkin/docker-compose.yml
- spring-cloud-sleuth-zipkin/pom.xml
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/DiscoveryClientEndpointLocator.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/EndpointLocator.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ServerPropertiesEndpointLocator.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinAutoConfiguration.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinProperties.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java
Zipkin now has Span.timestamp/duration, so no more need for
"aquire/release".
This also corrects the host/endpoint logged for timeline annotations, as
it should always be the local process.
See https://github.com/openzipkin/zipkin/blob/master/zipkin-thrift/src/main/thrift/com/twitter/zipkin/zipkinCore.thrift
> Updates to latest zipkin/brave 

- spring-cloud-sleuth-stream/pom.xml
- spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/ServerPropertiesHostLocator.java
- spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/SleuthStreamAutoConfiguration.java
- spring-cloud-sleuth-stream/src/test/java/org/springframework/cloud/sleuth/stream/ServerPropertiesHostLocatorTests.java
- spring-cloud-sleuth-zipkin-stream/pom.xml
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListener.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListenerTests.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ServerPropertiesEndpointLocator.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinAutoConfiguration.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/ServerPropertiesEndpointLocatorTests.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListenerTests.java
Fixes missing zipkin service name and polishes span converters.
Missing service name:
Zipkin service names were logged as null, which is invalid and led to
them showing up as "unknown" in the zipkin ui. This was due to a wiring
bug, and a special-case, which this change fixes.
The special-case was when a sleuth span had no annotations. Since zipkin
service names are attached to annotations, they are only queryable when 
annotations exist. When there are no annotations, we add the "lc" 
binary annotation, which makes that span attached to the correct service
in zipkin.
Polishing:
Zipkin timestamps were not always set as microseconds. This fixes that.
The de-facto label in zipkin for unknown service is "unknown". This
fixes the code, which formerly fell back to "application".
This also …
> Fixes missing zipkin service name and polishes span converters.

- README.adoc
- docs/src/main/asciidoc/README.adoc
- docs/src/main/asciidoc/features.adoc
- spring-cloud-sleuth-core/pom.xml
- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/src/main/java/sample/SampleMessagingApplication.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/src/main/java/sample/SampleRibbonApplication.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/src/main/java/tools/AbstractIntegrationTest.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin-stream/docker-compose.yml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin-stream/src/main/resources/application.yml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/docker-compose.yml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/java/sample/SampleZipkinApplication.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/test/java/integration/ZipkinDockerTests.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/test/resources/docker-compose.yml
- spring-cloud-sleuth-zipkin-stream/pom.xml
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/SamplingZipkinSpanIterator.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListener.java
- spring-cloud-sleuth-zipkin-stream/src/test/resources/application.yml
- spring-cloud-sleuth-zipkin/docker-compose.yml
- spring-cloud-sleuth-zipkin/pom.xml
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinAutoConfiguration.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinProperties.java
Recent versions of zipkin and brave operate with http instead of scribe.
This changes the implementation accordingly, as well adds a sampler to
the POST endpoint.
A notable impact is that we no longer require a collector process, as
the zipkin server's POST endpoint is a collector.
> Updates to latest zipkin and brave, removing Scribe dependency

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin-stream/src/main/resources/application.yml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/docker-compose.yml
- spring-cloud-sleuth-zipkin-stream/src/test/resources/application.yml
- spring-cloud-sleuth-zipkin/docker-compose.yml
Zipkin 0.4.1 obviates some duplication of configuration. It is also the
first version that's published as a docker image.
By switching to the published image of zipkin-java, we can be more
consistent, as `spring-cloud-sleuth-zipkin-stream` is derived from that,
not the scala query service.
> Updates to zipkin-java 0.4.1, particularly docker images

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/TraceManager.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/TraceKeys.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTraceManager.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/src/main/java/sample/SampleBackground.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-stream/src/main/java/sample/SampleBackground.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-stream/src/main/java/sample/SampleController.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/java/sample/SampleBackground.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/java/sample/SampleController.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/src/main/java/sample/SampleBackground.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/src/main/java/sample/SampleController.java
Previously, sleuth logged more data than necessary. This led to issues
including spans approaching megabytes each. This pares down default keys
to a minimal set, but allows users to opt-into logging more by extending
`TraceFilter`.
Closes #82
Closes #95 (Obviates)
> Pares down default http tags, but opens apis for adding more

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Log.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/log/JsonLogSpanListenerTests.java
- spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/StreamSpanListener.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListener.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListenerTests.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListenerTests.java
Span.logs are really timestamped events. This clarifies the naming and
documentation around that.
See https://github.com/opentracing/opentracing-go/pull/39
> Prefers the word event when adding to a Span's timeline

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/docker-compose.yml
- spring-cloud-sleuth-zipkin/docker-compose.yml
This includes better dependency aggregation than before. For example,
you no longer need mysql to view the dependency graph, as the in-memory
server supports aggregation now. Also, if you log "ca" on a root span,
the associated service will show on the dependency graph on the far
left. This allows you to show uninstrumented clients of note. Similarly,
if you log "sa" on a leaf node, the destination will show on the far
right. You'd use "sa" for uninstrumented services like databases, auth
servers or cloud apis.
Here's an example. Note you can now see the database service on the far right.
> Updates to zipkin-java 0.5

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/docker-compose.yml
- spring-cloud-sleuth-zipkin/docker-compose.yml
This includes updates to the latest zipkin-web image and zipkin-java
dependency.
zipkin-web's notable as it does a lot more in javascript, ex it no
longer does server-side mustache template rendering. It also makes one
less call to the services endpoint when rendering the search page.
zipkin-java's in-memory span store is now in the core jar and also can
render the dependency tree. This means it is now feature-parity with
mysql (but still merely a test span-store). zipkin-java also now tests
that it can run without optional dependencies.
> Updates to zipkin 0.5.3

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-zipkin/pom.xml
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/HttpZipkinSpanReporterTest.java
This replaces direct usage of MockWebServer with ZipkinRule.
See https://github.com/openzipkin/zipkin-java/pull/83
> Refactors HTTP SpanReporter tests to use ZipkinRule

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/docker-compose.yml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/test/java/integration/ZipkinTests.java
- spring-cloud-sleuth-zipkin/docker-compose.yml
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/HttpZipkinSpanReporter.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinAutoConfiguration.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinProperties.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/HttpZipkinSpanReporterTest.java
This updates to latest zipkin, adding a flag to gzip spans before
posting them. Note this is set to false by default as it requires servers
to also be latest. We can flip the default once we can assume that.
Ex. `spring.zipkin.compression.enabled = true`
> Updates to latest zipkin, adding spring.zipkin.compression.enabled flag

- index.html
Fix typo in url for zipkin https://github.com/openzipkin/zipkin.
> Fix bad zipkin project link in index.html

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/docker-compose.yml
- spring-cloud-sleuth-zipkin/docker-compose.yml
This is a maintenance update to zipkin which has no api impact.
* zipkin-server supports cassandra now
* zipkin-web is now javascript (even if still hosted on a scala process)
> Updates to latest zipkin 0.7

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/docker-compose.yml
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanList.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListener.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanListTests.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListenerTests.java
- spring-cloud-sleuth-zipkin/docker-compose.yml
Notably, this removes the "zipkin-web" dependency, as the UI is now
collocated on zipkin-server.
Other notable changes are Cassandra and Kafka support, as well removing
the Brave dependency.
> Updates to zipkin 0.9

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Log.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/LogTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTest.java
The Log object should never have a null entry as it is defined. This
change fixes that, backfills equals/hashCode for convenience, and adds
Jackson annotations that use the validating constructor.
This also adds a json annotation to span that allows logs to be
serialized. This is tested by round-tripping the json.
> Tightens Log to forbid null events and fixes Span json serialization

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
The problem resulted in wrong span durations. The issue was such that for the case where span from request has a parent that needs to be reported we didn't stop that parent. That means that it has value of 'end' equal to 0. In that situation the duration of Span was calculated as a difference between current time and the start time. We should never report spans that have not been stopped - otherwise that stopping will take place a lot of time later.
fixes #247
> Stopping parent before reporting

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jSpanLogger.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTracer.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/SpanContextHolder.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterIntegrationTests.java
when iterating over saved spans during span closing we can apply a function that should be executed on each iteration.
fixes #248
> Removing entries from MDC

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
No immediate impact to sleuth, but some notable changes underneath:
* zipkin.Sampler is now extensible to permit dynamic rate adjustments
* self-tracing can now be disabled even if Brave is in the classpath
* related property: zipkin.self-tracing.enabled
* brave-spancollector-scribe is no longer an optional dependency
In the world of plugins:
* Elasticsearch bugfix on traces w/ more than 10 spans
* New ZooKeeper adaptive collection-tier sampler
> Updates to zipkin 0.14

- spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/StreamSpanReporter.java
- spring-cloud-sleuth-stream/src/test/java/org/springframework/cloud/sleuth/stream/StreamSpanListenerTests.java
now instead of first passing all the spans from the queue to the list and then clearing it we're now draining it contents. If in the meantime any spans will arrive they will be rained at next passing
fixes #259
> Draining from queue instead of clearing it

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListener.java
Notably, this removes the accidental transient dependency on scala, by
removing the dependency on `zipkin-cassandra-core`. Related classes have
been vendored into `storage-cassandra`.
This also splits out `CollectorSampler` as its own thing and introduces
two options for instrumentation sampling:
* `BoundaryTraceIdSampler` - For high-volume sites, based on Finagle
* `CountingTraceIdSampler` - Trades lower performance for high accuracy
> Updates to zipkin 0.15

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanList.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListener.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/HttpZipkinSpanReporterTest.java
Relating to sleuth, this is mostly cosmetic with a kafka condition fix.
It might be of interest that `GET /api/v1/traces` no longer requires
parameters.
https://github.com/openzipkin/zipkin-java/releases/tag/0.18.0
> Updates to zipkin 0.18

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin-stream/README.md
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin-stream/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin-stream/src/test/java/example/ZipkinServerApplicationTests.java
- spring-cloud-sleuth-zipkin-stream/README.md
- spring-cloud-sleuth-zipkin-stream/pom.xml
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListener.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinServerApplicationTests.java
This moves to changes made in preparation of zipkin 1.0.
Here are the notables:
* Zipkin has autoconfiguration modules, where maven artifacts have the prefix 'zipkin-autoconfigure-X'
* Zipkin's ui now shares a version with everything else
* Zipkin now namespaces packages and configuration. ex zipkin.storage.X as opposed to zipkin.X
* All autoconfiguration classes are prefixed `Zipkin` to be easier to find
* Zipkin binds components like StorageComponent, as opposed to individual classes like SpanStore.
* Health checks are under the scope "zipkin" and broken down by component
* UI responsiveness is better by conditionally caching names queries for 5 minutes
* New `Collector` class, which makes logging and metrics patterns the same regardless of transport
> Moves to zipkin 0.21

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/HttpTraceKeysInjector.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceAsyncClientHttpRequestFactoryWrapper.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebAsyncClientAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/SleuthFeignBuilder.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClient.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClientAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignObjectWrapper.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignRequestInterceptor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/assertions/SpanAssert.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceContextPropagationChannelInterceptorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/websocket/TraceWebSocketAutoConfigurationTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/RestTemplateTraceAspectIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterAlwaysSamplerIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterCustomExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterMockChainIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptorIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/WebClientDiscoveryExceptionTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/WebClientExceptionTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/WebClientTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignClientServerErrorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/common/AbstractMvcIntegrationTest.java
This PR introduces additional tags on the HTTP client side. Before sending a request we're tagging the client side with HTTP Trace Keys so that if the other side is not working / not instrumented (e.g. call to an external service) then the debugging information remains.
Feign Client Side:
Rest Template Client Side:
Server Side:
Related to #290 
CC @dsyer @adriancole
> Issues #290 client tags

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAspect.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/WebClientTests.java
- spring-cloud-sleuth-core/src/test/resources/logback.xml
with this change trace filter is not closing all spans. It's closing only spans when the response is successful. If the response status is 4xx,5xx then an exception controller should start processing the response. At the end of the day an aspect will close the span once the controller has finished processing.
fixes #278
> Added aspect that closes spans for wrong http responses

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rxjava/SleuthRxJavaSchedulersHook.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/HttpTraceKeysInjector.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/TracePostZuulFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/TracePreZuulFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/TraceRestClientRibbonCommandFactory.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/TraceZuulAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jSpanLogger.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/assertions/ListOfSpans.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/assertions/ListOfSpansAssert.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/assertions/SleuthAssertions.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/WebClientTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/TraceRestClientRibbonCommandFactoryTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/TraceZuulIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/log/Slf4JSpanLoggerTest.java
- spring-cloud-sleuth-core/src/test/resources/application.yml
- spring-cloud-sleuth-core/src/test/resources/logback.xml
- spring-cloud-sleuth-dependencies/pom.xml
- `TraceFilter` no longer is a `OncePerRequestFilter`
- `TraceFilter` processes the request that is executed upon `ERROR` dispatch (the logs will be present there)
- Altered the logic in `TraceFilter` that an already processed request will not be detached (which resulted in an exception)
- Added some debugging to instrumentation
- Added assertion over a list of spans
- Bumped up SC-Netflix to 1.1.2.BUILD-SNAPSHOT
- Added Zuul integration tests
- Added Http keys injection to Zuul client call
> Fixed the issues with Zuul exception handling

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessagingSpanExtractor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/MessagingSpanExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterMockChainIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
with this change we will throw an IllegalStateException when the malformed tracing data are sent. In TraceFilter we're catching it and sending back 400 response. In case of messaging the exception gets propagated
fixed #306
> Throwing exception when tracing is malformed

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
Changes since 1.1.1 related to cassandra or json parsing.
See https://github.com/openzipkin/zipkin/releases/tag/1.1.5
> Updates to zipkin 1.1.5

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAspect.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/TracePostZuulFilter.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterCustomExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/WebClientExceptionTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/WebClientTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/TraceZuulIntegrationTests.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/src/test/java/integration/MessagingApplicationTests.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/src/main/java/tools/AbstractIntegrationTest.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/test/java/integration/ZipkinTests.java
The change results in converting the artificial span spawned from the first http server span into a span that is generated from an aspect that wraps a controller that processes the request.
cc @dsyer
> Renaming child server span

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTracer.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanList.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanListTests.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListenerTests.java
Formerly, `Span.getAccumulatedMillis()` worked, but could returns
imprecise measurements, particularly local spans. This changes the
internals of Span to keep track of a start tick. Using this, it can
return a more precise `Span.getAccumulatedMicros()`.
To ensure this precision isn't lost in serialization, this adds a
json field `durationMicros`, which is only set when the span is stopped.
This is set instead of start tick because `System.nanoTime()` is JVM
specific and so cannot be used across the network. `durationMicros` uses
null instead of zero comparisons because nano time can be negative.
Fixes #312
Example cold trace from https://github.com/adriancole/sleuth-webmvc-example/
Example warm trace from https://github.com/adriancole/sleuth-webmvc-example/
> Exposes getAccumulatedMicros for more precise Span duration

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceSpringIntegrationAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptorTests.java
Makes use of property place holders to set the `patterns` attribute of the `@GlobalChannelInterceptor` annotation used for the `TraceChannelInterceptor`. As supported by the annotation, only simple
patterns are supported.
Added the Spring configuration metadata for `spring.sleuth.integration` properties.
Fixes gh-323
> Added patterns to @GlobalChannelInterceptor

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
This is particularly important for the mysql backend, as the bundled
schema now allows dependency aggregation.
See https://github.com/openzipkin/zipkin/releases/tag/1.5.0
> Updates to Zipkin 1.5

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
Using the e.g properties from Zipkin Consumer gives the following error when loading the zipkin-server ui:
```
ERROR: cannot load service names: zipkin/storage/mysql/internal/generated/tables/ZipkinAnnotations
ERROR: cannot load span names: zipkin/storage/mysql/internal/generated/tables/ZipkinSpans
```
So to fix it you have to explicitly add username and password for the mysql storage. This is because in zipkin-sever the  [zipkin-server.yml](https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/resources/zipkin-server.yml) does not have default values for username and password at mysql storage type.
> Fixing config properties for Zipkin Consumer

- spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/SleuthStreamAutoConfiguration.java
- spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/SleuthStreamProperties.java
- spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/StreamSpanReporter.java
- spring-cloud-sleuth-stream/src/test/java/org/springframework/cloud/sleuth/stream/SleuthStreamAutoConfigurationTest.java
- spring-cloud-sleuth-stream/src/test/java/org/springframework/cloud/sleuth/stream/StreamSpanListenerTests.java
Added configurable PollerMetadata bean to be used with the Inbound
Channel Adapter in the StreamSpanReporter. Fixed delay and max messages
per poll are configurable via configuration properties. Implementors can
provide a bean of type PollerMetadata and name
StreamSpanReporter.POLLER to take full control of the poller.
Fixes: gh-338
> Added PollerMetadata for StreamSpanReporter

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
This updates to Zipkin 1.6, which targets Spring Boot 1.4
Zipkin 1.6 also corrects default values around the UI, which should lead
to better search performance.
> Updates to Zipkin 1.6 (which is Spring Boot 1.4)

- docs/pom.xml
- docs/src/main/asciidoc/ghpages.sh
- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
What we're missing ATM is different documentation versions for different application versions. WIth changing the gh-script what I've managed to achieve is:
- presenting the version of the application in the docs
- checking out the Git branch (e.g. 1.0.x)
- checking out the application version from pom  (e.g. 1.0.5.BUILD-SNAPSHOT)
- checking out what is the name of the main adoc file (e.g. spring-cloud-sleuth)
- pulling the changes from gh-pages after checkout (we're missing that everywhere IMO...)
- in gh-pages creating a folder with name of the version (e.g. /1.0.5.BUILD-SNAPSHOT)
- copying all the `docs/target/generated-docs/` to that folder
- if the branch from which we're calling the script is NOT master then I'm changing the `spring-cloud-sleuth.html` to `index.html` so that it's …
> Deploying documentation to proper folder

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterWebIntegrationMultipleFiltersTests.java
after making TraceFilter process different dispatch types we've introduced a bug related to filter ordering. TraceFilter was registered with a default ordering which is of lowest precedence.
With this change we ensure that the ordering of TraceFilter is fixed.
Fixes #380
> Fixing TraceFilter order

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
Sleuth doesn't create I64 binary annotations, but others might. This
version of zipkin fixes an encoding bug when someone logs a binary
annotation of type I64.
> Fixes edge-case encoding bug

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
Luckily, someone reported a bug where if unprintable characters were in
the json, the UI would hose. This version fixes that.
> Updates to Zipkin 1.8.4

- spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/StreamEnvironmentPostProcessor.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/StreamEnvironmentPostProcessor.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListener.java
Rely on the `contentType` header of the transported message to
tell Spring Cloud Stream how to coerce the message to `Span`.
> Use StreamListener for coercing messages from JSON `Span`

- benchmarks/pom.xml
- pom.xml
- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-zipkin/pom.xml
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/HttpZipkinSpanReporter.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ReporterMetricsAdapter.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/RestTemplateSender.java
AsyncReporter is a more robust version of what we were doing before.
Notably, it can give a memory threshold instead of span count for the
backlog. This change ports to use AsyncReporter internally.
See https://github.com/openzipkin/zipkin-reporter-java#asyncreporter
> Reroutes HttpZipkinSpanReporter to use zipkin.reporter.AsyncReporter

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractorTests.java
The first step of transitioning to 128bit `X-B3-TraceId` is tolerantly reading 32 character long ids by throwing away the high bits (any characters left of 16 characters). This allows the tracing system to more flexibly introduce 128bit trace id support in the future.
Ex. when `X-B3-TraceId: 463ac35c9f6413ad48485a3953bb6124` is received, parse the lower 64 bits (right most 16 characters ex48485a3953bb6124) as the trace id.
See https://github.com/openzipkin/b3-propagation/issues/6
> Tolerate reads of 128 bit X-B3-TraceId

- benchmarks/pom.xml
- pom.xml
- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-zipkin/pom.xml
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/HttpZipkinSpanReporter.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ReporterMetricsAdapter.java
AsyncReporter is a more robust version of what we were doing before.
Notably, it can give a memory threshold instead of span count for the
backlog. This change ports to use AsyncReporter internally.
See https://github.com/openzipkin/zipkin-reporter-java#asyncreporter
> Reroutes HttpZipkinSpanReporter to use zipkin.reporter.AsyncReporter (1.0.x)

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ReporterMetricsAdapter.java
while we don't send this info, AsyncSpanReporter has backlog metrics now.
aside: we could make an actuate module to expose all of these, if we wanted
> Updates to adjust for reporter metrics drift

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanList.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListenerTests.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/DiscoveryClientEndpointLocator.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ServerPropertiesEndpointLocator.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/FallbackHavingEndpointLocatorTests.java
Now that Endpoint has ipv6, the factory method is even worse than it
was before. This switches to a builder instead.
Note: Endpoint now has a nice toString which should help debugging.
> Updates to latest Zipkin and avoids Endpoint factory method

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceThreadPoolTaskExecutor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptorTests.java
Some components in Spring assume (perhaps wrongly) that a channel
interceptor will not convert a mutable message into an immutable one, and
they continue to modify the headers dowstream. We can dosge the issue of
whether this is right or wrong by keeping the message headers mutable, just
in case.
> Ensure message headers are still mutable after interceptor is called

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceCustomFilterResponseInjectorTests.java
This is to add documentation on how to add trace/span related headers to http response as discussed in #424
> #424 - Documentation for adding trace/span headers to http response

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
* Support for MySQL 5.7 with SQL_MODE=ONLY_FULL_GROUP_BY
* Includes support to store 128-bit trace ID (not yet implemented here)
See https://github.com/openzipkin/b3-propagation/issues/6
> Updates to zipkin 1.14.4

- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/src/test/java/integration/MessagingApplicationTests.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanList.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanListTests.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ZipkinMessageListenerTests.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListenerTests.java
This ensures spans that have remote set to true don't send
Span.timestamp/duration.
In the RPC span model, the client owns the timestamp and duration of the
span. If we were propagated an id, we can assume that we shouldn't
report timestamp or duration, rather let the client do that. Worst case
we were propagated an unreported ID and Zipkin backfills timestamp and
duration.
See https://github.com/openzipkin/openzipkin.github.io/issues/49
> Ensures Span.timestamp/duration are not reported on remote spans

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/ApacheHttpClientRibbonRequestCustomizerTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/OkHttpClientRibbonRequestCustomizerTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/RestClientRibbonRequestCustomizerTests.java
Before, we were using variable encoding for trace and span identifiers.
This complicates search for those who are copy/pasting fixed-length IDs
provisioned upstream. This moves to standard formatting, while
maintaining tolerant reads.
The code added will also be used to support 128-bit (32 char) trace IDs.
Fixes #449
> Switches ID encoding to fixed-length

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/TraceRestClientRibbonCommandFactoryTest.java
Before, we were using variable encoding for trace and span identifiers.
This complicates search for those who are copy/pasting fixed-length IDs
provisioned upstream. This moves to standard formatting, while
maintaining tolerant reads.
The code added will also be used to support 128-bit (32 char) trace IDs.
Backport of #450
> Switches ID encoding to fixed-length (1.0.x backport)

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/HeaderBasedMessagingExtractor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/HeaderBasedMessagingInjector.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/ZipkinHttpSpanExtractor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/ZipkinHttpSpanInjector.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/SpanInjectingRibbonRequestCustomizer.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jSpanLogger.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/issues/issue410/Issue410Tests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/MessagingSpanExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceCustomFilterResponseInjectorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterCustomExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/log/Slf4JSpanLoggerTest.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanList.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanListTests.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListenerTests.java
This supports 128-bit traces via a new field traceIdHigh, which matches
other zipkin implementations. In encoded form, the trace ID is simply
twice as long (32 hex characters).
With this change in, a 128-bit trace propagated will not be downgraded
to 64-bits when sending downstream, reporting to Zipkin or adding to
the logging context.
This will be followed by a change to support initiating 128-bit traces.
See https://github.com/openzipkin/b3-propagation/issues/6
> Propagates logs and reports 128-bit trace IDs

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessagingSpanExtractor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessagingSpanInjector.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpRequestInjector.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/RequestContextInjector.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jSpanLogger.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/issues/issue410/Issue410Tests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/MessagingSpanExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceCustomFilterResponseInjectorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/log/Slf4JSpanLoggerTest.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanList.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanListTests.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListenerTests.java
This supports 128-bit traces via a new field traceIdHigh, which matches
other zipkin implementations. In encoded form, the trace ID is simply
twice as long (32 hex characters).
With this change in, a 128-bit trace propagated will not be downgraded
to 64-bits when sending downstream, reporting to Zipkin or adding to
the logging context.
This will be followed by a change to support initiating 128-bit traces.
> Propagates logs and reports 128-bit trace IDs (1.1.x)

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/SleuthProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTracer.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationTest.java
This adds autoconfiguration to create 128-bit traces when
`spring.sleuth.traceId128=true`.
> Starts 128-bit traces when spring.sleuth.traceId128=true

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/SleuthProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTracer.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationTest.java
This adds autoconfiguration to create 128-bit traces when
`spring.sleuth.traceId128=true`.
See #455
> Starts 128-bit traces when spring.sleuth.traceId128=true (1.0.x backport)

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
Applications using custom HTTP status codes are currently having issues with Spring Cloud Sleuth.
`TraceFilter.httpStatusSuccessful()` is throwing an IllegalArgumentException on `HttpStatus.valueOf(response.getStatus())`.
This can be fixed by replacing in `TraceFilter.httpStatusSuccessful()`
```java
HttpStatus httpStatus = HttpStatus.valueOf(response.getStatus());
return httpStatus.is2xxSuccessful() || httpStatus.is3xxRedirection();
```
with
```java
HttpStatus.Series httpStatusSeries = HttpStatus.Series.valueOf(response.getStatus());
return httpStatusSeries == HttpStatus.Series.SUCCESSFUL || httpStatusSeries == HttpStatus.Series.REDIRECTION;
```
> Custom HTTP status codes support

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceExecutor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/SpanContinuingTraceCallable.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/SpanContinuingTraceRunnable.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceContinuingCallable.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorService.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableScheduledExecutorService.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/hystrix/TraceCommand.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAspect.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTracer.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/documentation/SpringCloudSleuthDocTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/LocalComponentTraceCallableTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceCallableTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceRunnableTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorServiceTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceableScheduledExecutorServiceTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixConcurrencyStrategyTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/hystrix/TraceCommandTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterMockChainIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceAsyncListenableTaskExecutorTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptorIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignRetriesTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClientTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/TracePostZuulFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/TracePreZuulFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/trace/DefaultTracerTests.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/HttpZipkinSpanReporterTest.java
with this change we change the approach to continue spans (if they already exist) instead of starting new ones. The RPC spans would still be generated but Hystrix, Async, Callables / Runnables will reuse an existing span if there is one.
the scenarios are as follows:
Assuming that we have a trace X with span Y
* if you used `tracer.wrap(Callable)` or `trace.wrap(Runnable)` then:
* previously you'd get a span Z created when the Callable / Runnable is executed
* with this change you'll continue the span Y
* if you used a `HystrixCommand` then
* previously you'd get a span Z together with added tags when the command got executed
* with this change you'll continue the span Y and the tags will be added to span Y
* if you used a `ExecutorService` then
* previously you'd get a span Z together …
> Continuing Spans

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/TraceKeys.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceHandlerInterceptor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceRequestAttributes.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTracer.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/assertions/ListOfSpansAssert.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/servererrors/FeignClientServerErrorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/integration/WebClientTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/view/Issue469.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/view/Issue469Tests.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/src/test/java/integration/MessagingApplicationTests.java
without this change an explicit new span is created on the server side. Its name is equal to the method name of the controller. It introduces some nice advantages in terms of readability of trace.
with this change we're continuing a previous span on the server side. We're attaching the tags and logs to that span with information about controller class and controller name. Also events related to start and finish of the controller are there.
fixes #471 #469 #427
> Spans are continued in Handler Interceptors

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/SleuthProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rxjava/RxJavaAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rxjava/SleuthRxJavaSchedulersProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/scheduling/SleuthSchedulingProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/scheduling/TraceSchedulingAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthWebProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/SleuthLogAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/SleuthSlf4jProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/metric/SleuthMetricProperties.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternProviderConfigTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterMockChainIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
As we discussed in https://github.com/spring-cloud/spring-cloud-sleuth/issues/477 and gitter I created configuration properties for all properties used in spring-sleuth-core. 
I have used additional-spring-configuration-metadata.json for single `enabled` properties.
In case of camel case property name it resolves both `skip-pattern` and `skipPattern`, but I'd rather update documentation to use conventional property names.
Also `spring.sleuth.rxjava.schedulers.ignoredthreads` looks strange without word separator, we can add new one called `ignored-threads` and deprecate old one, what do you say?`
> Created @ConfigurationProperties classes and updated additional metadata

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/NeverRetry.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/SleuthFeignBuilder.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/SleuthHystrixFeignBuilder.java
This is needed to make the changes in spring-cloud/spring-cloud-netflix#1457 work when Sleuth is on the classpath.  Do not merge until that pull request is merged into Netflix.
Also changes will need to be made in the 1.1.x branch.  But for that branch we can use the `NEVER_RETRY` class from OpenFeign since a more recent version is in that branch.
> Disable Feign Retry

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
I have a use case where we have the time where an event took place but not the ability to create the log as it happens. This method will allow us to still log those events to sleuth.
This also makes the OpenTracing adapter I am working on more feature complete so that is good too.
> Add a new log method to span that allows for setting the time

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceAsyncRestTemplate.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClient.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/assertions/ListOfSpansAssert.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/exception/WebClientExceptionTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignRetriesTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClientTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/integration/WebClientTests.java
without this change there's a problem with the time when the SS is set on a span. Currently it's done in TraceFilter's finally block. The problem is that this code is executed after the response has been sent back to the client. Thus CR sometimes was set faster than SS (it doesn't make any sense from the logical point of view).
with this change we're introducing wrappers over the `HttpServletResponse` where we annotate the span with `SS` just after the response gets sent to the recipient.
fixes #492 #431
> Fixing the moment when SS is set

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceEnvironmentPostProcessor.java
Use `spring.zipkin.service.name` if present.
> Display overriden service name in logs (addition to #487)

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/DefaultSpanCreator.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/SleuthAdvisorConfig.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/SleuthAnnotationAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAnnotationDisableTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAnnotationNoSleuthTests.java
Also updated tests that were expecting missing `SpanTagAnnotationHandler` when `spring.sleuth.enabled` or `spring.sleuth.annotations.enabled` is false, because this one is not spring bean anymore
> Moved adding annotated parameters from span creator to interceptor

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/SleuthAdvisorConfig.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectTests.java
I think it may be useful to have `error` tag if it was threw in annotated method.
Only one concern that we are rethrowing an exception and `error` tag will also be present in all parent spans created through annotation and span from web filter. WDYT?
> Adding error tag when exception occurs in SleuthInterceptor

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClientAutoConfiguration.java
Exactly like `HystrixFeignConfiguration`:
https://github.com/spring-cloud/spring-cloud-netflix/blob/c89645e0699342c55314e3ef7a2c6eb8b6ac90de/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientsConfiguration.java#L97
> Use HystrixFeign only if it's present on classpath

- spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/SleuthStreamAutoConfiguration.java
Fix #556
* Explicitly state that `StreamSleuthAutoConfiguration` should
execute before `TraceAutoConfiguration`;
* Also ensure that `ChannelsEndpointAutoConfiguration` is configured
after `StreamSleuthAutoConfiguration` to ensure that the bound
channels are added to the `/channels` actuator endpoint
> Fix autoconfiguration ordering with Sleuth Stream

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceRequestAttributes.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/TracePostZuulFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/TracePreZuulFilter.java
without this change when dealing with Zuul, it's TraceFilter that is closing a span on error
with this change we're allowing the PostZuulFilter to close that span and TraceFilter doesn't interfere
fixes #563 
cc @brenuart
> Making post zuul filter close the span on error

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/HeaderBasedMessagingExtractor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/ZipkinHttpSpanExtractor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/assertions/SpanAssert.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/HeaderBasedMessagingExtractorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractorTests.java
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanList.java
- spring-cloud-sleuth-zipkin-stream/src/test/java/org/springframework/cloud/sleuth/zipkin/stream/ConvertToZipkinSpanListTests.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListenerTests.java
whenever
- a span or trace id get generated when a request / message arrives
- child span is created
we set the field to false
whenever we find ids in the incoming request / message we set the field to true
fixes #696
> Introduced a "shared" field in Span

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTracer.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/trace/DefaultTracerTests.java
Amazon will throw out trace IDs that aren't associated with a recent
timestamp. This encodes the current epoch seconds into the first 32
of a 128-bit trace ID to support conversion to an Amazon Root ID.
See #459
> Encodes epoch seconds into first 32bits of a 128-bit trace ID

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/SleuthProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterAlwaysSamplerIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterMockChainIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/common/AbstractMvcIntegrationTest.java
This adds the ability to opt out of span sharing between the client and
server side of an RPC. This is important when reporting to systems that
do not share span IDs, such as Google Stackdriver and Amazon X-Ray.
Note: this still defaults to true, in favor of existing Zipkin
implementations. See https://github.com/openzipkin/zipkin/issues/1480
See #395
See #459
> Adds spring.sleuth.supports-join to disable span ID sharing

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptorTests.java
When the X-SPAN-NAME HTTP Header is built from a URI that contains non ASCII characters (in its decoded form), Sleuth generates a value for the header that violates RFC 822 (Section 3.1.2) which states the value "may be composed of any ASCII characters, except CR or LF.  (While CR and/or LF may be present  in the actual text, they are removed by the action of unfolding the field.)" When Apache 2 is used as proxy server in the same environment this results in the following errors.
[Mon Oct 09 11:22:15.421634 2017] [core:debug] [pid 9550] protocol.c(1151):
[client 10.104.87.215:39868] AH02427: Request header value is malformed:
https:/rowSets/cas~fs~åˆ’
[Mon Oct 09 11:22:15.421664 2017] [core:debug] [pid 9550] protocol.c(1309):
[client 10.104.87.215:39868] AH00567: request failed: error …
> Non-ASCII characters included in X-SPAN-NAME header.

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/src/main/java/sample/SampleFeignApplication.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/src/test/java/integration/IntegrationTestZipkinSpanReporter.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/src/test/java/integration/MessagingApplicationTests.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/src/main/java/sample/SampleRibbonApplication.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/src/main/java/tools/AbstractIntegrationTest.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin2/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin2/src/test/java/integration/ZipkinTests.java
- spring-cloud-sleuth-zipkin/pom.xml
- spring-cloud-sleuth-zipkin2/pom.xml
- spring-cloud-sleuth-zipkin2/src/test/java/org/springframework/cloud/sleuth/zipkin2/ZipkinDiscoveryClientTests.java
This does two things: ensures samples don't use Zipkin v1 in any way,
and misaligns the version numbers of zipkin v1 and zipkin v2 apis.
This is an attempt to walk around the gradle plugin issue, which only
exists when someone is using both versions of zipkin.
See https://github.com/spring-projects/spring-boot/issues/10778
> Misaligns Zipkin v1 from sharing the same version number as v2

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceEnvironmentPostProcessor.java
The JavaDoc and implementation have drifted, since the previously included logic for aspects is no longer needed in 2.x. This removes mention of the aspects from the class JavaDoc.
> JavaDoc fix to match implementation

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/InternalApi.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/AsyncDefaultAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceAsyncAspect.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/InternalApiTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriberTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceAsyncIntegrationTests.java
without this change, we always create a new span in `TraceAsyncAspect`. That's because the span created via `LazyTraceExecutor` (which is executed before the aspect), contains no useful information. 
with this change we're renaming the `LTE` span in `TraceAsyncAspect`. We're using an `InternalApi` class that we kindly ask that nobody uses. 
fixes #661 #783
> Continuation of async spans

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
- spring-cloud-sleuth-zipkin-legacy/pom.xml
- spring-cloud-sleuth-zipkin/pom.xml
Under load, the previous version of zipkin-reporter's AsyncReporter
caused a lot of overhead. This version fixes that by ensuring encoding
is deferred and not done inside a lock.
```
± |master ?:1 ✗| → wrk -t4 -c64 -d30s http://localhost:8081
Running 30s test @ http://localhost:8081
4 threads and 64 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   137.99ms  147.36ms   1.19s    85.00%
Req/Sec   204.56    139.00   656.00     67.53%
18963 requests in 30.05s, 2.57MB read
Requests/sec:    631.10
Transfer/sec:     87.61KB
± |master ?:1 ✗| → wrk -t4 -c64 -d30s http://localhost:8081
Running 30s test @ http://localhost:8081
4 threads and 64 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    41.72ms   30.04ms 280.43ms   67.68%
Req/Sec   411.32     79.74 …
```
> Moves to significantly more performant zipkin-reporter

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptorTests.java
without this change for DirectChannel `beforeHandle` and `afterHandle` were not called at all
with this change we're removing any hacks and we're executing those methods
fixes gh-821
> Fixes DirectChannel support

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceHttpAutoConfiguration.java
Instrumentation around brave is more likely to use a simple bean name
like "tracing" vs "sleuthTracing". This changes the commodity beans to
simple names so that we can avoid having to teach naming prefixes unless
necessary.
This affects the following beans:
* httpTracing
* tracing
* tracer
* spanCustomizer
This came up when integrating dubbo, as their [extension loader](https://github.com/alibaba/dubbo/blob/master/dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/extension/SpringExtensionFactory.java#L43) prefers
stable bean names. For example, loading `brave.Tracing` with their
spring extension silently failed because our bean was named
"sleuthTracing". Even if we can provide instructions to override this,
seems best to dodge.
> Prefers "plain bean names" for community instrumentation

- spring-cloud-sleuth-zipkin/pom.xml
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/sender/RestTemplateSenderTest.java
There was some doubt on gitter about sleuth generating spans with floating-point
rendered timestamps. While this shouldn't break people we certainly shouldn't
create json like this.
This was presumed to be caused by sleuth's rest template sender by @mojsha who
was trying Jaeger. Jaeger's parser doesn't give any errors with a 400.
```json
[
{
"traceId": "a65dac9d8bbb57f8",
"parentId": "a65dac9d8bbb57f8",
"id": "f223bb97e1eba9b2",
"kind": "SERVER",
"name": "https:\/hello3",
"timestamp": 1.521027116604e+15,
"duration": 1525,
"localEndpoint": {
"serviceName": "${spring.application.name}",
"ipv4": "10.128.6.98",
"port": 8443
},
```
I added a test to make sure it is not the case.
> Adds test to make sure RestTemplate sender doesn't mess with json

- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-zipkin-stream/README.md
- spring-cloud-sleuth-zipkin-stream/pom.xml
- spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/EnableZipkinStreamServer.java
Our docs deprecated the spring-cloud-sleuth-zipkin-stream, but the
project didn't.
> Moves to latest Zipkin and formally deprecates the stream server

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessageHeaderPropagation.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/MessageHeaderPropagationTest.java
Handle sleuth tracing headers sent from spring-kafka as byte[] in Spring Cloud Stream sleuth tracing so propagation works as expected.
Similar to https://github.com/openzipkin/brave/blob/master/instrumentation/kafka-clients/src/main/java/brave/kafka/clients/KafkaPropagation.java#L21
> Handle sleuth headers sent from spring-kafka as byte[] in Spring Cloud

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessageHeaderPropagation.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptorTest.java
when getting an `ErrorMessage` we have 2 pairs of headers. The headers from the `ErrorMessage` and the headers from the payload which also is a message. The payload that happens to be a message contains the tracing headers. We need to extract these to retrieve the tracing context. HOWEVER these are the only headers we are interested in. We MUST NOT copy any other headers than the tracing ones to a new message that we will return from the method.
fixes gh-946
> Sleuth no longer corrupts Error message in Spring Integration

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthWebProperties.java
Updates the default skip pattern to include the Spring Boot 2 root Actuator endpoint `/actuator`.
See #737
> Skip tracing root Actuator endpoint

- pom.xml
- spring-cloud-sleuth-core/pom.xml
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SleuthHttpClientParserTests.java
- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
same as Brave 4, but without any deprecated methods (or deprecated dependencies like io.zipkin.java:zipkin)
> Updates to Brave 5

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriber.java
This is done by implementing NO-OP QueueSubscription on the subscriber
and removing the guard against `Fuseable` publisher sources.
As `Fuseable` is a marker interface there should be no reason for code
to perform casts so for now the fact that the `lift` call in
ReactorSleuth doesn't actually produces a `Fuseable` publisher should
not be a problem.
> fix #994 Make SpanSubscriber fake fuseability

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rxjava/SleuthRxJavaSchedulersHook.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/documentation/SpringCloudSleuthDocTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SpringDataInstrumentationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/multiple/MultipleHopsIntegrationTests.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/src/test/java/integration/MessagingApplicationTests.java
The latest version of Brave corrects a data merge problem where shared
spans (created via Tracer.joinSpan) would lose some data. Along the way,
this fixes some misuse of `Tracer.joinSpan` which should only be used
for RPC server spans.
See https://github.com/openzipkin/brave/pull/734 applied in Brave 5.1.3
> Adjusts expectations of data reporting of loopback spans

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/AsyncAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/AsyncProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessor.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/spring.factories
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessorTests.java
We have a spring-boot application (spring-boot-starter-parent-2.0.0.RELEASE) using spring-cloud-starter-zipkin for writing "spans" to zipkin.
We use spring-integration too (through spring-boot-starter-integration) and we have added an integration flow with a PollableChannel to be used within a poller:
```
@Bean
public PollableChannel pollableChannel() {
return new QueueChannel(100);
}
@Bean
@ServiceActivator(poller = @Poller(taskExecutor="batchTaskExecutor"), 
inputChannel= "pollableChannel")
public MyHandler myHandler() {
return new MyHandler();
}
```
Since adding this configuration, we are having an "asynch" span every second. I raised a question in stackoverflow -> https://stackoverflow.com/questions/51438273/zipkin-asynch-span-every-second. So after investigating the issue, it turned …
> ability to disable instrumentation in ThreadPoolTaskExecutor

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthWebProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceHttpAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/RestTemplateTraceAspectIntegrationTests.java
without this change there's no way to filter outbound requests basing on the path via a property.
with this change we're introducing that
fixes gh-1047
> Added an option to filter out outbound requests

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceSpringIntegrationAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptor.java
without this change there's no easy way to work with message headers for Spring Integration
with this change we're allowing to register beans that will override the default behaviour
fixes gh-1032
> Added option to override message headers

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- pom.xml
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/documentation/SpringCloudSleuthDocTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceAsyncAspectTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceAsyncListenableTaskExecutorTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceCallableTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceRunnableTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorServiceTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceableScheduledExecutorServiceTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixConcurrencyStrategyTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/hystrix/TraceCommandTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/ITTracingChannelInterceptor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptorTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/opentracing/BraveTracerTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/rxjava/SleuthRxJavaSchedulersHookTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceRestTemplateInterceptorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptorIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignRetriesTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignAspectTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TracingFeignClientTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/TracePostZuulFilterTests.java
- spring-cloud-sleuth-dependencies/pom.xml
Notably, this avoids `Span.remoteEndpoint` and deprecated test helpers.
(same as 6eca1249994d3ce63b5eabd21178e250f0fd9f80 on 2.0.x)
> Updates to latest Brave, removing deprecated usage

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/ReactorSleuthMethodInvocationProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriber.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriptionProvider.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectFluxTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriberTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriberTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfigurationAccessorConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFluxTests.java
- Use onLastOperator instead of onEachOperator
- Do not instrument scalar publishers
- Do not inject ScopePassingSubscriber if there is no span.
- Revisit ReactorSleuthMethodInvocationProcessor to reduce ops overhead
- Use only one operator for the MethodInvocationProcessor
- Warning Behavior Change: @NewSpan will defer Span creation/context
```java
@NewSpan Mono<Long> method() {
//before this was working
//tracer.currentSpan().context().spanId();
//Now it is deferred by subscribe
return Mono.defer(() -> Mono.just(tracer.currentSpan().context().spanId()));
}
//The reason being you want to start a new span for each subscribe:
Mono<Long> m = method();
m.subscribe(); //span1
m.subscribe(); //span2
@ContinueSpan Mono<Long> method() {
//Note this is still working
Long span = …
```
> Optimize Reactor Instrumentation

- pom.xml
- spring-cloud-sleuth-dependencies/pom.xml
This moves to latest Brave which fixes a regression. Basically, if you used an instrumentation which leaks spans or adds data after a span was finished... this abandoned data wouldn't end up flushed to zipkin. This was found in OpenTracing instrumentation.
Note: I don't know if the prior version used by Sleuth had the regression or not, but I know 5.3.3 did not.
cc @tutufool who identified the problem.
> Fixes a problem where leaked spans didn't end up in Zipkin

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternProviderConfigTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/issues/issue971/DemoSleuthSkipApplicationTests.java
Previously, all endpoints under the set context path would be skipped. Instead, this skips only Actuator endpoints under the set context-path.
Resolves #1146
---
We might want to reconsider the current approach, though. Previously, the management context path was appended to the default pattern instead of added as an OR to the pattern. The default pattern includes more things than just the Actuator endpoints, which won't be skipped if a context path is set currently. Also, if the Actuator base path is set to `/` then the approach in this change will have issues because it will again skip all endpoints for the application. This should be an improvement in most cases, though.
> Skip only Actuator endpoints when context path set

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/propagation/TagPropagationFinishedSpanHandler.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/spring.factories
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationAutoConfigurationTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/propagation/TagPropagationFinishedSpanHandlerTest.java
As part of this conversation - https://github.com/spring-cloud/spring-cloud-sleuth/issues/1071#issuecomment-415447228
by default this feature is disabled, but if someone what to propagate baggage to spans in order to enable filtering by it - they could use this feature, by just adding needed property.
In this way we are omitting changing code as described here - https://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html#_baggage_versus_span_tags
> sleuth extra propagation fields to tags feature.

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/AsyncAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/AsyncDefaultAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ContextRefreshedListener.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ContextUtil.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceExecutor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceThreadPoolTaskExecutor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorService.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableScheduledExecutorService.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorServiceTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceableScheduledExecutorServiceTest.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/ZipkinAutoConfigurationTests.java
without this change, for deferred JPA bootstrap, we're trying to get a bean very early and we have a deadlock
with this change, we only do it once the context is refreshed
the concept was such that I have a bean `ContextRefreshedListener` which is also an `AtomicBoolean`. Now, before we wrap any executor related logic, we use the `ContextUtil` to verify if the context is in the creation or not. There, we retrieve the `ContextRefreshedListener` bean and cache it. Only after `ContextRefreshedEvent` was received, will we start wrapping the executor services.
fixes #1128
> Only wrap executors when context is refreshed

- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/ZipkinBackwardsCompatibilityAutoConfiguration.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/ZipkinAutoConfigurationTests.java
Because the auto configuration order changed, we also had to adapt the condition
> Fixed backwards compatibility condition

- spring-cloud-sleuth-dependencies/pom.xml
gRPC spring boot version 3.0.1 (gRPC 1.16.1).
Fixes #1186. With this change, `io.github.lognet:grpc-spring-boot-starter:3.0.1` and `io.zipkin.brave:brave-instrumentation-grpc:5.6.0` have same gRPC version.
> gRPC spring boot version 3.0.1 (gRPC 1.16.1)

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceHttpAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationPropagationCustomizationTests.java
I work on the app that had in the past problems with deployment reproducibility. The app couldn't boot due to unresolved cycles between beans. After inspecting the problem, it turned out to be related to jar packaging. The order of classes within jar had an impact on Spring beans loading, so if you took jar known to have cycles and run it multiple times, you got always unresolved cycles. If you took it and repackaged classes and run, it was quite common for an app to boot properly. 
My solution to that problem was to disable resolving circular references between beans altogether and fix each cycle by hand by remodelling relationships between beans or delaying bean creation. This pr removes cycles in configuration classes so that Sleuth can be used by apps with `setAllowCircularReferences` …
> Remove cycles from auto configuration

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternProviderConfigTest.java
The Issue
======
While `Spring Cloud Sleuth` is constructing the skip patterns, the management/actuator web endpoints should be excluded from traces (addressed in https://github.com/spring-cloud/spring-cloud-sleuth/pull/1150/files and related PRs). However, when the management/actuator server is running on a different (from the application server) port, the skip patterns are still constructed using the application server context path.
Example:
```
server.port = 8080
server.servlet.contextPath = /api
management.server.port = 9080
management.endpoints.web.base-path = /mgt
```
The expected skip patterns (for `/info` and `health|` endpoints): 
```
/mgt/(info|info/.*|health|health/.*)
```
The current skip patterns (for `/info` and `health|` endpoints) are still using application context path: …
> Check if management server (actuator) is running on different port while constructing skip patterns

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
Currently you mention only one library for grpc spring-boot support, but there are currently two main libraries.
[LogNet/grpc-spring-boot-starter](https://github.com/LogNet/grpc-spring-boot-starter/) only supports the server side, whereas [yidongnan/grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter) supports the server and client side, as well as Spring-Security and other features.
Please also mention the second library.
**Disclosure:** I'm one of the core maintainers of [yidongnan/grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter).
> Also mention the net.devh:grpc-spring-boot-starter library

- .mvn/wrapper/maven-wrapper.properties
- benchmarks/pom.xml
- docs/pom.xml
- docs/src/main/asciidoc/ghpages.sh
- mvnw
- mvnw.cmd
- pom.xml
- spring-cloud-sleuth-core/pom.xml
- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml
- spring-cloud-sleuth-zipkin/pom.xml
- spring-cloud-starter-sleuth/pom.xml
- spring-cloud-starter-zipkin/pom.xml
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch migrated to:  
https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch ([https](https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch) result 200).
* http://stackoverflow.com/questions/29300806/a-bash-script-to-check-if-a-string-is-present-in-a-comma-separated-list-o …
> URL Cleanup

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
We are using `spring-cloud-gateway`(Greenwich.RELEASE), and with `spring-cloud-starter-zipkin` together, and we are using `HttpClient` like the following:
```
import reactor.netty.http.client.HttpClient;
@Compoment
public class InitClass{
@Resource
private HttpClient httpClient; 
@PostConstruct
public void initSomeThing(){
httpClient.request(HttpMethod.GET).uri("http://ip:port")
.responseContent().aggregate().asString(Charset.defaultCharset())
.subscribe(s -> System.out.println(s));
}
}
```
When executing this code,  the following error occurs:
```
13:15:17.002 WARN  [reactor-http-kqueue-3,,,,172.16.61.86] i.n.u.c.AbstractEventExecutor[AbstractEventExecutor.java:165] -> A task raised an exception. Task: reactor.netty.resources.PooledConnectionProvider$DisposableAcquire@65a15442 …
```
> Fix NullPointerException

- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternProviderConfigTest.java
Hey @marcingrzejszczak , @shakuzen !
As discussed (in https://github.com/spring-cloud/spring-cloud-sleuth/pull/1208), it would be good to switch the  `SkipPatternProviderConfigTest ` to use application context runner instead of manually instantiated configurations classes.
Thanks!
> Refactored SkipPatternProviderConfigTest to use WebApplicationContextRunner instead of manually instantiated configurations

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessageHeaderPropagation.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
- src/checkstyle/checkstyle-suppressions.xml
Since for some reason, the native headers sometimes are immutable even though the accessor says that the headers are mutable, then we have to ensure their mutability. We do so by first making a mutable copy of the native headers, then by removing the native headers from the headers map and replacing them with a mutable copy
fixes #1184
> Added a workaround for the mutability of native headers

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessorTests.java
Hi. I have a ScheduledExecutorService bean in context which is decorated with TraceableExecutorService. The problem is that the Scheduled part became missing and I could no longer inject this bean as ScheduledExecutorService, only as ExecutorService. I propose to adjust the decoration mechanism to check if it is scheduled or not.
> Decorate with Traceable Scheduled Executor service

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessorTests.java
When proxying the various Executor interfaces in ExecutorbeanPostProcessor, the decision of whether or not to use a cglib proxy was determined by checking if the bean's class is final, but final methods would also cause issues when using cglib. A common example of such an implementation is DelegatingSecurityContextScheduledExecutorService, which has final methods. (see #1336).
To resolve the issue with ThreadPoolTaskExecutor, AsyncTaskExecutor, and ExecutorService, fall back to the JDK proxy if the bean has any final methods.
> Fix proxying of executors with final methods

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceExchangeFilterFunctionHttpAdapterTests.java
> Return 0 status code on exception or invalid code

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/ProbabilityBasedSampler.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/sampler/ProbabilityBasedSamplerTests.java
When `spring.sleuth.sampler.probability` property is missing, instantiating `ProbabilityBasedSampler` throws an NPE during an attempt to autobox a null probability.
This PR adds an assertion with a user-readable error message.
> Add null check for sampler probability property

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationAutoConfigurationTests.java
- spring-cloud-sleuth-core/src/test/resources/application-tag-propagation.yml
> Remove ConditionalOnProperty for supporting yaml

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/grpc/SpringAwareManagedChannelBuilder.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessagingAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthHttpClientParser.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRequestHttpHeadersFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jScopeDecorator.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/propagation/TagPropagationFinishedSpanHandler.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/log/Slf4JSpanLoggerTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationAutoConfigurationTests.java
cleares any MDC entries that match a whitelist entry for baggage or propagation key even if the `ExtraPropagation` API wasn't called.
> Automatically removes mdc

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixConcurrencyStrategy.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixConcurrencyStrategyProperties.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixConcurrencyStrategyTest.java
Draft proposal for #1431.
Passthrough is disabled by default which means that the current behaviour will not change with this change.
When `spring.sleuth.hystrix.strategy.passthrough` is enabled, the HystrixConcurrencyStrategy will just pass the trace context to the Hystrix execution thread instead of using TraceCallables.
This way we propagate tracing information but don't create . spans for each execution.
> Add passthrough mode to HystrixConcurrencyStrategy

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorService.java
TraceableExecutorService swallows Exception because `execute` submits a Runnable and ignores the Future's result. It should call the delegates `execute` method instead of the `submit`.
> Fix TraceableExecutorService

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessor.java
- tests/spring-cloud-sleuth-instrumentation-async-tests/src/test/java/org/springframework/cloud/sleuth/instrument/async/issues/issue410/Issue410Tests.java
Purpose:
ThreadPoolTaskExecutor is not instrumented properly. Only methods inherited from AsyncTaskExecutor are intercepted, but TaskScheduler ones are lost. Added additional check to fix the issue.
> Fix ThreadPoolTaskScheduler proxy mechanism

- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/ZipkinRabbitSenderConfiguration.java
- spring-cloud-sleuth-zipkin/src/main/resources/META-INF/additional-spring-configuration-metadata.json
without this change we're reusing the same broker for application logic and sending spans to zipkin
with this change we're adding a property to allow providing a different set of addresses for brokers to send spans to Zipkin
fixes gh-1210
> Added parametrization of RabbitMQ brokers

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationCustomizersTests.java
Changes verification in TraceAutoConfiguration.sleuthPropagation()
to not skip customization if at least one ExtraFieldCustomizer is
defined.
Without this fix the customizers are only applied when either
baggage-keys or propagation-keys property is defined.
Fixes gh-1454
> Prevent ignoring of ExtraFieldCustomizer

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- pom.xml
- spring-cloud-sleuth-core/pom.xml
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessagingAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceSpringIntegrationAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceSpringMessagingAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingMethodMessageHandlerAdapter.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/spring.factories
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/ITTracingMethodMessageHandlerAdapterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/SqsQueueMessageHandlerTests.java
partially addressed #1217 
Attempts to make spring-messaging generic component for use elsewhere `TracingMethodMessageHandlerAdapter`. I'm still thinking about how to abstract/wrap the existing classes so code doesn't have to me copied from the Impl on the other side
> SQS Messaging Autoconfig

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/AsyncAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/AsyncDefaultAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceThreadPoolTaskScheduler.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/SleuthAsyncProperties.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/AsyncDisabledTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceThreadPoolTaskSchedulerTests.java
Recently, `AsyncAutoConfiguration` auto-instruments executors. This
causes spans named 'async' with no tag or other metadata to help
understand what is happening. It was somewhat difficult troubleshooting
this because the control is by bean name, but for example the "async"
span doesn't include the bean name.
For starters, this allows people to opt-out of automatically spanning
executors via `spring.sleuth.async.enabled=false`
See https://github.com/spring-cloud/spring-cloud-gcp/issues/1978
cc @meltsufin @saturnism
> Adds the possibility to opt-out of executor decoration

- spring-cloud-sleuth-core/pom.xml
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationTests.java
Since I'm no metrics expert I need feedback from such as experts as @shakuzen @adriancole @msmsimondean and the rest of the experts interested in this topic ;)
I've added an initial implementation that uses `counter`s and `gauge`s from micrometer for metrics. I've passed some default values for metric names but I'm not sure if those are the best.
This would actually start defaulting to the Micrometer version of a metric reporter since it's pretty much always on the classpath. If someone doesn't have a `meterRegistry` bean, then the in memory option will be taken into account.
I don't think we can have an option that there is no micrometer on the classpath since it comes with boot.
UPDATE: As @spencergibb mentioned, micrometer comes as an dependency with an actuator, however actuator …
> Use Micrometer metrics instead of in memory one

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- pom.xml
- spring-cloud-sleuth-core/pom.xml
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/circuitbreaker/SleuthCircuitBreakerAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/circuitbreaker/SleuthCircuitBreakerProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/circuitbreaker/TraceFunction.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/circuitbreaker/TraceSupplier.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/spring.factories
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/circuitbreaker/CircuitBreakerIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/circuitbreaker/CircuitBreakerTests.java
First take on the integration with `spring-cloud-circuitbreaker`.
We could provide options such as `TraceSupplier` and `TraceFunction` to manually wrap any commands that are executed via a circuit breaker. If Spring beans are involved we will wrap the `CircuitBreakerFactory` that the generated circuit breaker implementation always wraps the supplier and function in a trace representation.
> Spring Cloud Circuit Breaker tracing

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java
- tests/spring-cloud-sleuth-instrumentation-webflux-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFluxTests.java
This pull request improves on the instrumentation of WebFlux requests when the routes are defined using `RouterFunction` rather than in a `@Controller`. In particular:
- Before this patch, the operation name used to be just the HTTP verb like `get`, but now it will include the pattern like: `get /api/books/{id}`. This brings parity with the `@Controller` case.
- The `mvc.controller` tag used to be unset but now it will be set to the name of the router function, such as `BooksRouterService$$Lambda$123/123456789`. While this is not perfect, at least it points you to the right file to look at.
> Report HTTP pattern and handler function name for functional WebFlux routes.

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceExchangeFilterFunctionHttpClientResponseTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/integration/WebClientTests.java
Currently the `WebClient` tracing implementation ignores the `spring.sleuth.web.client.skip-pattern` property. This pull request fixes that.
> WebClient tracing should respect skipPattern.

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/opentracing/OpentracingAutoConfiguration.java
`OpentracingAutoConfiguration` exposes an `io.opentracing.Tracer` bean. To create this bean a `brave.Tracing` bean is required. The presence of `@ConditionalOnBean(Tracing.class)` ensures that this configuration is only applied when the bean is available.
`TraceAutoConfiguration` exposes a `brave.Tracing` bean. To ensure this bean is always available when applying `OpentracingAutoConfiguration` it is necessary to express this dependency. I've done so here by adding an `@AutoConfigureAfter` to ensure this auto configuration is applied after `TraceAutoConfiguration`.
Without this in place the `io.opentracing.Tracer` is created only when the order happens to work out in our favor.
> Configure OpentracingAutoConfiguration after TraceAutoConfiguration.

- docs/src/main/asciidoc/intro.adoc
Based on the grok example from the docs, a Filebeat + Logstash stack will produce the following:
- a `@timestamp` field based on the time that filebeat sends the log to logstash, as timestamp type.
- a `timestamp` field from the Spring Boot log, as string type.
In order to use the Spring Boot timestamp as the real Logstash `@timestamp` I use the following filters after the grok pattern:
```
date {
match => ["timestamp", "ISO8601"]
}
mutate {
remove_field => ["timestamp"]
}
```
Using these filters will result in `@timestamp` being the Spring Boot's timestamp, as a timestamp type, and will remove the now duplicated (string type) `timestamp`.
> Use actual log timestamp as logstash timestamp

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/AbstractSleuthMethodInvocationProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/ReactorSleuthMethodInvocationProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriber.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriber.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriptionProvider.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectFluxTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectMonoTests.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriberTests.java
This switches to pass around and use `TraceContext` instead of `Span` in
Reactor's context to take advantage of `maybeScope` which is far cheaper
than `withSpanInScope` when the span is already current. This also kills
some extra scope checks and any other accidental calls noticed.
The performance improvement here, I can't quantify as haven't done any
JMH on it.
cc @anuraaga
> Reduces overhead when using reactor by avoiding redundant context syncs

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/LazyBean.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriber.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriber.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/LazyBeanTests.java
There are numerous places where code defensively guards access to
BeanFactory methods. This centralizes the code, first using in reactor
as that's the more performance sensitive.
This also weaves in feedback from #1541 given by @simonbasle and @robotmrv
More unit tests are needed, but raised to ensure the approach is fine.
> Extracts LazyBean and backports reactor code to use it

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfigurationAccessorConfiguration.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfigurationAccessorConfiguration.java
Probably due to code drift, `HookRegisteringBeanDefinitionRegistryPostProcessor.setupHooks`
was used as an object method, which led to a confusing no-op chain in
tests.
This ensures it is used consistently as a static method, and also
corrects a bean accidentally marked static for testing.
> Corrects HookRegisteringBeanDefinitionRegistryPostProcessor.setupHooks

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/internal/LazyBean.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/ReactorNettyHttpClientSpringBootTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/integration/WebClientTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/internal/LazyBeanTests.java
This consolidates access to the `HttpTracing` bean so that the overhead
of netty `HttpClient` is reduced. It also pulls the reactor-netty test
into its own file.
> Reduces the amount of times getBean is invoked from reactor-netty

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/ReactorNettyHttpClientSpringBootTests.java
This shows how a span started in reactor-netty's `HttpClient` cannot
be closed, if an error occurs in `doOnRequestError()`.
> Refactors reactor-netty and shows doOnRequestError propagation break

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignBlockingLoadBalancerClient.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignObjectWrapper.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TracingFeignObjectWrapperTests.java
- tests/spring-cloud-sleuth-instrumentation-feign-tests/src/test/java/org/springframework/cloud/sleuth/instrument/feign/issues/issue1125/ManuallyCreatedLoadBalancerFeignClientTests.java
IMPORTANT: Only merge after  https://github.com/spring-cloud/spring-cloud-commons/pull/691 and https://github.com/spring-cloud/spring-cloud-openfeign/pull/300 are merged.
> Adjust to changes in FeignBlockingLoadBalancer client constructor.

- spring-cloud-sleuth-core/pom.xml
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/ReactorNettyHttpClientBraveTests.java
During other change, I noticed a lot of bugs in the instrumentation of
reactor-netty `HttpClient`. This uses Brave's integration tests to show
what works and what doesn't.
> ReactorNettyHttpClientBraveTests

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/ReactorNettyHttpClientBraveTests.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TestCallbackSubscriber.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/WebClientBraveTests.java
This also normalizes how we subscribe to request monos.
> Ensures spring context is closed in brave tests

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
In looking at underlying HttpClient mechanics, I noticed the reactor
call doesn't happen until subscribe. Before this change, we started the
client span at the ExchangeFilterFunction, not at subscribe time.
> Fixes WebClient which started a client span prior to a subscription

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignAspect.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignObjectWrapper.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TracingFeignClient.java
This tries to pick in the relevant changes made in 3813cf9dd47f98db0e075412abbffbd9d6742974
Notably, there's one glitch, `TraceFeignAspect` still passes bean, not
wrappedBean. The latter trips out `ManuallyCreatedLoadBalancerFeignClientTests`
as the nonexistenturl raises a hard error in Ribbon. I *think* this is a bug and
tests need to just adjust for that, but need a second opinion. Also, I'm not
entirely sure the intent of using the broken url then asserting against a
success result..
> Attempts to align feign code with master

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessorTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/integration/WebClientTests.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/ITSpringConfiguredReactorClient.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/ReactorNettyHttpClientBraveTests.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TestHttpCallbackSubscriber.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/WebClientBraveTests.java
in order to test typical concerns common to all reactor based clients, this makes a base type. Afterwards, we can do things like canceled subscriptions and make sure both WebClient and Reactor's HttpClient (both of which are pinned to reactor's types) get tested.
> Adds base integration test for reactor clients and adds cancelation tests

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternSampler.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthWebProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceHttpAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignAspect.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignContext.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternProviderConfigTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternSamplerTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceHttpAutoConfigurationTests.java
- tests/spring-cloud-sleuth-instrumentation-feign-tests/src/test/java/org/springframework/cloud/sleuth/instrument/feign/issues/issue1125/ManuallyCreatedLoadBalancerFeignClientTests.java
- tests/spring-cloud-sleuth-instrumentation-feign-tests/src/test/java/org/springframework/cloud/sleuth/instrument/feign/issues/issue1125delegates/ManuallyCreatedDelegateLoadBalancerFeignClientTests.java
- tests/spring-cloud-sleuth-instrumentation-feign-tests/src/test/java/org/springframework/cloud/sleuth/instrument/feign/issues/issue502/Issue502Tests.java
- tests/spring-cloud-sleuth-instrumentation-feign-tests/src/test/resources/application.yml
Before, the client sampler would only skip the path named ""! This was
the path used in one of the failing Feign tests, which made
troubleshooting like a murder mystery.
The "" is a regression in spring-cloud-openfeign noted below:
https://github.com/spring-cloud/spring-cloud-openfeign/pull/245/files#r403424379
> Fixes bugs in skip pattern code and Feign tests

- README.adoc
- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/PropertyBasedBaggageConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/multiple/MultipleHopsIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/opentracing/BraveTracerTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/log/Slf4JSpanLoggerTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/propagation/TagPropagationFinishedSpanHandlerTest.java
spring.sleuth.local-keys and spring.sleuth.remote-keys make sense
together, especially as baggage-keys will be removed.
> Renames spring.sleuth.propagation-keys to remote-keys

- README.adoc
- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/PropertyBasedBaggageConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/SleuthProperties.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationCustomizersTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationPropagationCustomizationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/multiple/DemoApplication.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/multiple/MultipleHopsIntegrationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/opentracing/BraveTracerTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/log/Slf4JSpanLoggerTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/propagation/TagPropagationFinishedSpanHandlerTest.java
The `spring.sleuth.baggage-keys` property assigned two headers for each
baggage. This causes unnecessary overhead and can be accomplished in another
way now:
```java
public class MyCode {
static final BaggageField USER_ID = BaggageField.create("userId");
@Autowired CurrentTraceContext currentTraceContext;
@Nullable
public String currentUserId() {
return USER_ID.getValue(currentTraceContext.get());
}
}
// In your @Configuration type, if you want to map multiple prefixes...
@Bean
BaggagePropagationConfig userIdBaggageConfig() {
return SingleBaggageField.newBuilder(MyBaggage.USER_ID)
.addKeyName("baggage-userId")
.addKeyName("baggage_userId")
.build();
}
```
> Deprecates spring.sleuth.baggage-keys property

- pom.xml
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/baggage/TraceBaggageAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessageHeaderPropagation.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessageHeaders.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationPropagationCustomizationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/MessageHeaderPropagationTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/PropagationSetterTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptorTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/opentracing/BraveTracerTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceRestTemplateInterceptorTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRequestHttpHeadersFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceResponseHttpHeadersFilterTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/integration/WebClientTests.java
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/src/main/java/tools/RequestSendingRunnable.java
- tests/spring-cloud-sleuth-instrumentation-messaging-tests/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/ITTracingChannelInterceptorTests.java
- tests/spring-cloud-sleuth-instrumentation-messaging-tests/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceContextPropagationChannelInterceptorTests.java
- tests/spring-cloud-sleuth-instrumentation-messaging-tests/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceStreamChannelInterceptorTests.java
- tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceCustomFilterResponseInjectorTests.java
- tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterIntegrationTests.java
- tests/spring-cloud-sleuth-instrumentation-webflux-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/GH1102Tests.java
- tests/spring-cloud-sleuth-instrumentation-webflux-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFluxTests.java
To reduce confusion and overhead, the following custom spring-messaging headers added in Sleuth 1.0 are no longer sent, and a log warning is issued once if they are by outside code.
* spanId
* spanSampled
* spanParentSpanId
* spanTraceId
* spanFlags
Sending the above headers actually increases the headers by up to 10 because they are duplicated in the "native" part of messages. This overhead is extreme especially if messages never leave the process.
The solution is to only send [b3 single format](https://github.com/openzipkin/b3-propagation#single-header), which has been in sleuth since 2.0 and is compatible with JMS. The B3 single format is always parsed and takes precedence, even if multiple headers are sent, so this is a safe change.
Note: Unlike RPC, messaging spans never join with …
> Stops propagating Sleuth 1.x spring-messaging headers

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/SamplerAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/SamplerCondition.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/sampler/SamplerAutoConfigurationTests.java
Sleuth is unlike most tracing configuration libraries, as it has a
legacy from 1.x as being primarily log correlation. In short, when
Zipkin is not installed, it ignored the sampling properties. This
behavior was managed implicitly through an untested combination of
configuration conventions between the core and zipkin modules.
16fb8e3 broke this and this change puts it back, in a way not tightly
coupled to Zipkin and neither requires the more simple, but confusing
"import SamplerAutoConfiguration" approach. It also backfills tests
that should have broken earlier.
In practice, a site that only uses logging is likely uniform in that, so
whether or not the sampled bit is set is of no consequence. However,
there's a chance that someone might rely on this historical behavior.
We should …
> Restores special case that ignores sampling properties

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfigurationIntegrationTests.java
Fixes #1599 
Had to wrestle a bit with the [sample project added by @jorgheymans](https://github.com/jorgheymans/sleuth-bug) by using `spring-cloud-dependencies:Hoxton.SR4` as parent adding the following two properties:
```
<brave.version>5.11.2</brave.version>
<spring-cloud-sleuth.version>2.2.3.BUILD-SNAPSHOT</spring-cloud-sleuth.version>
```
But after that, and with the changes on this PR cherry-picked into the Sleuth `2.2.x`  branch, I no longer see the message when starting that application. @jorgheymans can you confirm?
Not entirely sure if/how I could add a unit test to prove this works otherwise.
> Get KafkaStreamsTracing via BeanFactory to prevent eager initialization

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rpc/TraceRpcAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Without this commit, excluding `io.zipkin.brave:brave-instrumentation-rpc` from `spring-cloud-starter-zipkin` causes the following exception
```
java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.sleuth.instrument.rpc.TraceRpcAutoConfiguration.rpcTracing
at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-2.2.6.RELEASE.jar:2.2.6.RELEASE]
at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:184) …
```
> Enable to disable TraceRpcAutoConfiguration by just removing brave-instrumentation-rpc

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessagingAutoConfiguration.java
As same as #1628 , without this commit, excluding `io.zipkin.brave:brave-instrumentation-messaging` from `spring-cloud-starter-zipkin` causes the following exception
```
java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.sleuth.instrument.messaging.TraceMessagingAutoConfiguration.messagingTracing
at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-2.2.6.RELEASE.jar:2.2.6.RELEASE]
at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinit …
```
> Enable to disable TraceMessagingAutoConfiguration by just removing brave-instrumentation-messaging

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TracingFeignClient.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TracingFeignClientTests.java
there are some integration codes in out project making use of the requestTemplate, but after enable sleuth the reference is null. We found the reason here and the method of building the request is depracated
> replace method for deprecation and keep reference of requestTemplate

- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/ZipkinAutoConfiguration.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/ZipkinAutoConfigurationTests.java
I was surprised to see an executor service created just to make a time
limiter. This does it more simply and backfills the missing tests.
> Makes it more clear what the timeout code is doing and backfills tests

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/ExceptionLoggingFilter.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebServletAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/SleuthLogAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/spring.factories
- tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterWebIntegrationTests.java
- tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceWebServletAutoConfigurationTests.java
`ExceptionLoggingFilter` logs "Uncaught exception thrown" to error level
when there is a synchronous exception not otherwise swallowed. This is a
cure worse than the disease. This issue disables by default and the 3.x
should remove this, ending the years of problems it caused.
Fixes #1347
This was done IIUC to help @jfuerth who had log messages with trace IDs,
except the uncaught one, in #714 (Sept 2017). They were formerly told to
use `ExceptionHandler` and noted that didn't work in practice as it
subverted their status code logic.
Concretely, 4203566d87434e2cb65fbbb9b90fd92bac447f2e "solved" the issue
by having sleuth log all uncaught exceptions with the message
"Uncaught exception thrown". This code was initially embedded in
sleuth's and later pulled out to `ExceptionLoggingFilter` in …
> Deprecates ExceptionLoggingFilter and disables it by default

- benchmarks/pom.xml
- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- pom.xml
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/SpanAdjuster.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jCurrentTraceContext.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/SamplerCondition.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/SpanHandlerTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationPropagationCustomizationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/sampler/SamplerAutoConfigurationTests.java
- spring-cloud-sleuth-dependencies/pom.xml
- spring-cloud-sleuth-samples/pom.xml
- spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
- spring-cloud-sleuth-zipkin/pom.xml
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/ZipkinAutoConfigurationTests.java
- src/checkstyle/checkstyle-suppressions.xml
- tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterWebIntegrationTests.java
- tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/ITSpringConfiguredReactorClient.java
`SpanHandler` is the base type for the now deprecated `FinishedSpanHandler`.
Notable, it can not just handle things at the end of a recording, but also the
beginning.
For example, this permits set-once baggage without the HTTP abstraction:
```java
// assume this field is configured
static final BaggageField EPOCH_SECONDS = BaggageField.create("epoch_seconds");
static final class RootOnlyBaggage extends SpanHandler {
@Override
public boolean begin(TraceContext context, MutableSpan span, @Nullable TraceContext parent) {
if (EPOCH_SECONDS.getValue(context) == null) { // only set at the first span
long epochSeconds = System.currentTimeMillis() / 1000;
EPOCH_SECONDS.updateValue(context, String.valueOf(epochSeconds));
}
return true;
}
@Override public boolean end(TraceContext context, …
```
> Updates to Brave 5.12 and introduces SpanHandler

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/SleuthAnnotationProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/SleuthProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/SleuthAsyncProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/circuitbreaker/SleuthCircuitBreakerProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixConcurrencyStrategyProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthMessagingProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/opentracing/SleuthOpentracingProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SleuthReactorProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/redis/TraceRedisProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rxjava/SleuthRxJavaSchedulersProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/scheduling/SleuthSchedulingProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthHttpLegacyProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthHttpProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthWebProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/SleuthFeignProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/SleuthSlf4jProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/SamplerProperties.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/ZipkinProperties.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/ZipkinSenderProperties.java
I noticed we deleted many things without deprecation in 3.x and figured
deprecation was the right way. However, this doesn't work for auto-config
properties. This replaces deprecation with a TODO note to hide all the
types so that 4.x won't require guessing if someone externally is using
them directly or not.
> Replaces deprecated note on Properties with TODO to hide them in 3.x

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceAsyncCustomizer.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceAsyncTaskExecutor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceExecutor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceThreadPoolTaskExecutor.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceCallable.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceRunnable.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorService.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableScheduledExecutorService.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessagingAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rpc/TraceRpcAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceHttpAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebAsyncClientAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/SleuthSlf4jProperties.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/SamplerAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/jms/config/TracingJmsListenerEndpointRegistry.java
- spring-cloud-sleuth-core/src/main/resources/META-INF/spring.factories
This puts specific comments in as to why certain files that seem like they
shouldn't be public are. Notably, this includes entrypoint autoconfiguration,
which are sometimes order sensitive. In other cases there are types that were
documented (notably the async package).
This also untangles a few configuration.
> Pares back some deprecation after analyzing each file

- tests/spring-cloud-sleuth-instrumentation-async-tests/pom.xml
- tests/spring-cloud-sleuth-instrumentation-async-tests/src/test/java/org/springframework/cloud/sleuth/instrument/async/TraceAsyncIntegrationTests.java
I had flakes on TraceAsyncIntegrationTests and it was hard to tell why
as there were so many problems with it. It used a normal list in async
setting, it unnecessarily created extra spans, it added a hook inside
the async method which if passed only told you it was in the middle of
an op, not the end of it. The method danced around making failure in
console almost impossible to decipher.
This took me a few hours to make just a normal test. Hopefully, the
others will keep passing as I can't afford time to redo all of them.
> Rewrites async test to be less circuitous and more valid

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceBaggageConfiguration.java
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/propagation/SleuthTagPropagationProperties.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationPropagationCustomizationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceBaggageConfigurationTests.java
This allows integrations of Sleuth to use the same approach for 2.2.x as 3.x:
If you have a custom base propagation format, override the `BaggagePropagation.Factory`
bean instead of `ExtraFieldsPropagation.Factory`
Note: one subtle difference 2.2.x to 3.x is the change in the primary inject format.
2.2.x is
```java
return BaggagePropagation.newFactoryBuilder(B3Propagation.newFactoryBuilder()
.injectFormat(B3Propagation.Format.MULTI).build());
```
3.0 is
```java
return BaggagePropagation.newFactoryBuilder(B3Propagation.newFactoryBuilder()
.injectFormat(B3Propagation.Format.SINGLE_NO_PARENT).build());
```
per #1607
See https://github.com/spring-cloud/spring-cloud-gcp/issues/2268
> Backports BaggagePropagation to 2.2.x

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationTests.java
This is more prevention of a problem, then seeing one in practice.
Technically, a TracingCustomizer can order things backwards, and it hit
me in a test env (not sleuth).
> Ensures Zipkin handlers order last (after redacters etc)

- spring-cloud-sleuth-core/pom.xml
- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectFluxTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectMonoTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/discoveryexception/WebClientDiscoveryExceptionTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/exception/WebClientExceptionTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/sampler/SamplerAutoConfigurationTests.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/ZipkinAutoConfiguration.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/ZipkinAutoConfigurationTests.java
- tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterIntegrationTests.java
- tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterWebIntegrationTests.java
There was emmense work to prepare for decoupling of spring-cloud-sleuth-core
from Zipkin. This included complete test conversion and deprecations between
2.2.x and 3.0.x.
This moves all Zipkin related code to spring-cloud-sleuth-zipkin, making the
primary data recording tool `SpanHandler` as opposed to `Reporter<zipkin2.Span>`
For example, Wavefront and soon Stackdriver can implement `SpanHandler` and
skip conversion into the Zipkin model first. `SpanHandler` also includes
begin and end hooks which allow data extensions to be developed.
see https://github.com/wavefrontHQ/wavefront-spring-boot
> Drops zipkin dependency from spring-cloud-sleuth-core

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceBaggageConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationPropagationCustomizationTests.java
- tests/spring-cloud-sleuth-instrumentation-messaging-tests/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceContextPropagationChannelInterceptorTests.java
- tests/spring-cloud-sleuth-instrumentation-messaging-tests/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceStreamChannelInterceptorTests.java
This makes sure there cannot be JMS problems related to use of
hyphenated headers unless someone overrides the `Propagation.Factory`.
To avoid this, we set non-remote spans to B3 single format as done on
the 3.x branch here:
https://github.com/spring-cloud/spring-cloud-sleuth/pull/1607/files#diff-db43b7e91bd69d063333c20b947c902bR83-R84
Fixes #1643
> Uses B3 single for non-remote spans (2.2.x)

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/ReactorSleuthMethodInvocationProcessor.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectFluxTests.java
I introduced a bug on #1525 which resulted in restarting of a trace, instead of continuing one. This fixes the bug and backfills the missing test.
Thanks @adirepo for the tip
Fixes #1634
> Fixes bug where we didn't fall back to current span

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/SpanTagAnnotationHandler.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/NullSpanTagAnnotationHandlerTests.java
- tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterWebIntegrationTests.java
Hi,
I found that when I have request parameter that is optional (`null` when controller method invoked) with combination with `@SpanTag`, tag is handled incorrectly.
I have created PR that solves it. Please look at tests to see usecases (see `NullParameterController`).
What do you think?
Thx,
Ivos
> Optional/Null parameter used within @SpanTag

- spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/EndpointWithCyclicDependenciesTests.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternProviderConfigTest.java
- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/internal/LazyBeanTests.java
Actuator endpoints are queried to make the default skip pattern. There's an
edge case where actuator endpoints indirectly reference the still constructing
HttpTracing bean. Ex: an instrumented client could cause a cyclic dep.
This optimizes for the opposite: that custom actuator endpoints are not in
use. This allows configuration to be eagerly parsed, allowing any errors to
surface earlier. In the case there is a cyclic dep, this parsing becomes lazy,
deferring any errors creating the skip pattern.
Fixes #1679
> Permits Actuator endpoints to depend on HttpTracing

- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/RestTemplateSender.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/sender/RestTemplateSenderTest.java
The AsyncZipkinSpanHandler calls 'check' once on startup to let someone
know an error that may affect tracing up front. Before, this didn't
include the endpoint so it is less obvious what could be the problem.
Ex people goof the URL (don't add /api/v2/spans or it is added twice)
> Makes a nice toString on RestTemplateSender

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
* Added `WebClient.Builder` as a supported bean
* Updated verbiage since a `WebClient` can only be created by using one of the various factory methods and a `WebClient.Builder` can be created either by `new` or various factory methods.
Fixes https://github.com/spring-cloud/spring-cloud-sleuth/issues/1716
> Include WebClient.Builder in HTTP Client Integration docs

- docs/src/main/asciidoc/_index.adoc
While reading docs I found a small typo in index file. "propertie" instead of "properties", this commit fixes that.
> Fix typo in docs (index file)

- spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/bridge/BraveHttpServerRequest.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
Spring Cloud 2020.0.0 stopped setting the remote IP and port on traces coming from HTTP servlet requests. This change brings that functionality back.
> Set remote IP and port for servlet HTTP server traces.

- docs/src/main/asciidoc/project-features.adoc
The docs still contained a sample including the [removed](https://github.com/spring-cloud/spring-cloud-sleuth/wiki/Spring-Cloud-Sleuth-3.0-Migration-Guide#parentid-and-sampled-spanexportable-mdc-fields-names-are-no-longer-set) `spanExportable` field in the log entries.
> Remove spanExportable from sample log file entry in docs

- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/reactor/SleuthReactorProperties.java
- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/reactor/TraceReactorAutoConfiguration.java
- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/reactor/TraceReactorAutoConfigurationAccessorConfiguration.java
- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/web/TraceWebFluxConfiguration.java
- spring-cloud-sleuth-brave/src/test/java/org/springframework/cloud/sleuth/internal/LazyBeanTests.java
- spring-cloud-sleuth-instrumentation/pom.xml
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/annotation/ReactorSleuthMethodInvocationProcessor.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorHooksHelper.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriber.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/TraceContextPropagator.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/internal/LazyBean.java
- spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorHooksHelperTests.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/FlowsScopePassingSpanSubscriberTests.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriberSpringBootTests.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriberTests.java
this is rebased https://github.com/spring-cloud/spring-cloud-sleuth/pull/1733 on top of master (3.0.1-SNAPSHOT) + tests   
results of org.springframework.cloud.sleuth.benchmarks.jmh.webflux.MicroBenchmarkHttpTests to compare difference  
Before 
```
Benchmark                                                       (instrumentation)  (tracerImplementation)    Mode    Cnt       Score        Error   Units
MicroBenchmarkHttpTests.test                                      noSleuthComplex                   brave  sample   4294       2.330 ±      0.025   ms/op
MicroBenchmarkHttpTests.test:·gc.alloc.rate.norm                  noSleuthComplex                   brave  sample     10   38261.367 ±   2419.172    B/op
MicroBenchmarkHttpTests.test                                        onEachComplex …
```
> optimize reactor on_each instrumentation

- docs/src/main/asciidoc/spring-cloud-sleuth.adoc
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/ZipkinProperties.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/RestTemplateSender.java
- spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/ZipkinRestTemplateSenderConfiguration.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/ZipkinAutoConfigurationTests.java
- spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/sender/RestTemplateSenderTest.java
This comes in handy when another monitoring tool is being used, for instance new relic, which doesn't not require path in its tracing api.
Context as of feb 19, new relic doesn't accept request to its tracing api endpoint with path. Previous it was fine, now it will throw 404 erro.
> Implement mechanism to apply custom api path

- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/web/client/TraceWebClientAutoConfiguration.java
- spring-cloud-sleuth-autoconfigure/src/test/java/org/springframework/cloud/sleuth/autoconfig/instrument/web/client/GatewayAutoConfigurationTests.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRequestHttpHeadersFilter.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRequestHttpHeadersFilterTests.java
with this change we're doing both HeaderFilter based Gateway instrumentation and the Netty Client one.
with this change we're conditionally enabling the HeaderFilter instrumentation only when there is no Netty Client one present on the classpath.
fixes gh-1840
> Don't allow double Gateway instrumentation

- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceExchangeFilterFunction.java
- spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceExchangeFilterFunctionHttpClientResponseTests.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/integration/sampled/WebClientTests.java
Spans names are in the form `'<http method> <uri template>'`
(e.g. `'GET /path/{id}'`). This naming strategy matches the span names
generated by `TraceWebFilter`.
The improve naming strategy is not applied to `RestTemplate` as the uri
template is not readily available to interceptors and `RestTemplate` is
in maintenance mode.
This originally targeted `main` but has been switched to target 3.1.x instead #1934
> Modify WebClient tracing to include the uri template in generated span names

- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorHooksHelper.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
- spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorHooksHelperTests.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/FlowsScopePassingSpanSubscriberTests.java
remove custom Publisher decorators that were mostly copy of reactor-core Lift Publishers and use new LIFTER Scannable Attribute instead.
additional context:  
Reduces amount of code on Sleuth side as proposed here https://github.com/spring-cloud/spring-cloud-sleuth/pull/1830#issuecomment-774302906
> simplify ON_EACH reactor instrumentation

- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/integrations.adoc
- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/DataSourceProxyConfiguration.java
- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcProperties.java
- spring-cloud-sleuth-autoconfigure/src/test/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/ProxyDataSourceConfigurationTests.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/DataSourceProxyProperties.java
Fixes #1973 
@marcingrzejszczak @gavlyukovskiy can you please review this PR
- Aligned default values of `Query` & `SlowQuery` in `TraceJdbcProperties.DataSourceProxyProperties` and `DataSourceProxyProperties`
- Add code to copy properties of `Query` and `SlowQuery` in `DataSourceProxyConfiguration`
- Add test case to check if `log-level` can be overridden or not
> Fix not able to override datasource-proxy log-level

- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/web/SkipPatternConfiguration.java
Handle `BeanCreationException` instead of just `BeanCurrentlyInCreationException`.
This handles the case when a cyclic reference (causing a `BeanCurrentlyInCreationException`) occurs further down the creation stack ; when it is not the actuator that references the in-creation HttpTracing bean, but a dependency of that actuator. In this case the exception that bubbles up to here is an `UnsatisfiedDependencyException`, which is a `BeanCreationException`.
I originally made this issue, but instead have submitted the PR to reintroduce the change.
**Describe the bug**
In https://github.com/spring-cloud/spring-cloud-sleuth/pull/1722 a change was made to broaden the Exceptions caught in `SkipPatternConfiguration` due to the possibility of circular dependencies. It seems that when 2.2.x was merged …
> Regression: SkipPatternProvider doesn't handle all cyclic dependency cases

- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/actuate/TextOutputFormat.java
Fixes gh-1996
Change order of TextOutputFormat enum and give `CONTENT_TYPE_OPENZIPKIN_JSON_V2`
highest ordinal value, so that it will be matched first by spring-boot-actuator
and in case of default Accept header JSON data will be returned.
> Fix traces actuator should return json by default

- docs/src/main/asciidoc/integrations.adoc
It seems to be accidentally missed.
> Add property to disable Reactor support in docs

- docs/src/main/asciidoc/getting-started.adoc
Using `Backend.class` getLogger() argument in `Example.class` maybe a typo.
e.g)
```java
public class Foo {
private static final Logger log = LoggerFactory.getLogger(Foo.class);
}
```
> Fix typo in document example

- docs/src/main/asciidoc/using.adoc
Refer to SpanTagAnnotationHandlerTests.java, `@SpanTag(key = "test", expression = "'hello' + ' characters'")` produces `hello characters` value of tag.
https://github.com/spring-cloud/spring-cloud-sleuth/blob/2b17d08ee19b4b8e30d0343e633eaa900e6d2b8c/tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/annotation/SpanTagAnnotationHandlerTests.java#L74
So, `hello characters` is right value of tag in `Resolving Expressions for a Value` document section.
> Fix an example value using TagValueExpressionResolver

- spring-cloud-sleuth-api/src/main/java/org/springframework/cloud/sleuth/SpanAndScope.java
- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/DataSourceProxyConfiguration.java
- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/P6SpyConfiguration.java
- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcAutoConfiguration.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceJdbcEventListener.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceListenerStrategy.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceQueryExecutionListener.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/task/TraceTaskExecutionListener.java
- tests/brave/spring-cloud-sleuth-instrumentation-jdbc-tests/src/test/java/org/springframework/cloud/sleuth/brave/instrument/jdbc/TraceJdbcEventListenerTests.java
- tests/brave/spring-cloud-sleuth-instrumentation-jdbc-tests/src/test/java/org/springframework/cloud/sleuth/brave/instrument/jdbc/TraceQueryExecutionListenerTests.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceJdbcEventListenerTests.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceListenerStrategyTests.java
- tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceQueryExecutionListenerTests.java
Refactored `remoteServiceName` resolution logic to be easier to follow
Fixed `TraceQueryExecutionListener#getConnection` that leaks connection by acquiring (and not closing) additional connection from a `DataSource`
The main idea is to track current connection and only put it and statements/resultSets it creates into the scope. For most applications there will be only one connection and all resources are closed properly, but if it's not the case we'll not mess up the scope. 
The only change that I'm not sure about is that I changed `SpanAndScope` to have optional `Scope`, if that's not okay we can always track spans/scopes inside `ConnectionInfo`/`StatementInfo`/`ResultSetInfo`.
I have also removed getters from inner classes, as it seems more in line with other inner classes in Sleuth.
> Refactored TraceListenerStrategy to better track current scope in case multiple connections are used

- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/redis/TraceLettuceClientResourcesBeanPostProcessor.java
Implementations of ClientResources are stateful and must be shutdown after they are no longer in use. 
This PR will fix https://github.com/spring-cloud/spring-cloud-sleuth/issues/2059
> Shutdown unused ClientResources

- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/instrument/redis/BraveRedisAutoConfiguration.java
- spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/redis/TraceLettuceClientResourcesBeanPostProcessor.java
- spring-cloud-sleuth-brave/pom.xml
- spring-cloud-sleuth-instrumentation/pom.xml
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/redis/ClientResourcesBuilderCustomizer.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/redis/TraceLettuceClientResourcesBuilderCustomizer.java
Extracted Brave-specific Redis instrumentation to use the Sleuth API, and registered the implementation in Brave autoconfiguration.
Fixes gh-2045
> Use Sleuth API for Redis instrumentation

- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/SpanNameProvider.java
- spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceListenerStrategy.java
- spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/jdbc/SpanNameProviderTest.java
My previous PR #2086 has been merged before I could respond to the comments. I've created another PR with some improvements suggested in the previous PR.
@gavlyukovskiy I've used regex instead of doing substring. I've figured substring(6) would be a result of lucky coincidence that all known query types (select, update, insert, delete) have 6 chars. If someone in the future wanted to add another type - for example BEGIN or ALTER - then they would have a refactoring problem in their hands. Now all that would need to be done is to add the new type to the list of 'known' types.
I've also extracted the span 'generation' into separate class that can be now tested, so that it's also somewhat documented now.
Please let me know if that works better.
> #2083 improvements
